version: "3"
services:
  traefik:
    image: traefik:1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80

  multitool:
    image: praqma/network-multitool
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:example.com,www.example.com
